[package]
name = "axum_bookclub"
version = "0.1.0"
edition = "2021"

[lib]
name = "axum_bookclub"
path = "src/lib.rs"

[[bin]]
name = "axum_bookclub"
path = "src/main.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
